on: 
  workflow_dispatch:
  

name: Create EKS cluster

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Congigure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Test AWS credentials
      run: aws sts get-caller-identity

    - name: Create EKS cluster
      run: |
        eksctl create cluster --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} \
          --nodegroup-name standard-workers --node-type t3.medium --nodes 3 --nodes-min 1 --nodes-max 4 --managed
