apiVersion: ec2.services.k8s.aws/v1aplpha1
kind: VPC
metadata:
  name: vpc
spec:
  cidrBlocks:
    - 10.0.0.0/16
  enableDNSupport: true
  enableDNSHostnames: true
  tags:
    - key: name
      value: vpc-ctrl
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: security-group
spec:
  description: "ack security group"
  name: sg
  vpcRef:
    from:
      name: vpc
  ingressRules:
    - ipProtocol: tcp
      fromPort: 22
      toPort: 22
      ipRanges:
        - cidrIP: "0.0.0.0/0"
          description: "ingress"
